/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CaseCard: typeof import('./components/case-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBadge: typeof import('./components/ScoreBadge.vue')['default']
    SkeletonCard: typeof import('./components/skeleton-card/index.vue')['default']
    SubscribeBanner: typeof import('./components/subscribe-banner/index.vue')['default']
    TagMor: typeof import('./components/TagMor.vue')['default']
  }
}
