/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CaseCard: typeof import('./components/CaseCard.vue')['default']
    EmptyTip: typeof import('./components/EmptyTip.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBadge: typeof import('./components/ScoreBadge.vue')['default']
    SubscribeBanner: typeof import('./components/SubscribeBanner.vue')['default']
    TagMor: typeof import('./components/TagMor.vue')['default']
  }
}
